<div class="content">
    <div class="message_wait">
        Une partie est en cours, veuillez attendre que celle-ci se termine
    </div>
    <script></script>
</div>
<div class="content_right wait">
    Les autres joueurs en attente
    <div class="player_list">
        <div class="player_item">
            <div class="left">
                <div class="circle" style="background-color: green;"></div>
            </div>
            <div class="right">
                <div class="name">ThiboJ</div>
                <div class="stats">
                    <img src="img/game/players/victory.png" alt="img_victory">
                    10
                    <img src="img/game/players/defeat.png" alt="img_defeat">
                    7
                </div>
            </div>
        </div>
        <div class="player_item">
            <div class="left">
                <div class="circle" style="background-color: yellow;"></div>
            </div>
            <div class="right">
                <div class="name">ThiboJ</div>
                <div class="stats">
                    <img src="img/game/players/victory.png" alt="img_victory">
                    10
                    <img src="img/game/players/defeat.png" alt="img_defeat">
                    7
                </div>
            </div>
        </div>
        <div class="player_item">
            <div class="left">
                <div class="circle" style="background-color: red;"></div>
            </div>
            <div class="right">
                <div class="name">ThiboJ</div>
                <div class="stats">
                    <img src="img/game/players/victory.png" alt="img_victory">
                    10
                    <img src="img/game/players/defeat.png" alt="img_defeat">
                    7
                </div>
            </div>
        </div>
    </div>
</div>




<script type="text/javascript" src="<?php echo $this->url("home")?>js/game/gamebegin.js"></script>
<script>
    baseUrl = "<?php echo $this->url("home")?>";
    verifNewGame();
</script>