<div class="content">
    <script type="text/javascript" src="js/admin/game.js"></script>
    <div class="">
        <input type="button" class="bouton_lancement" onclick="lancer_partie( this , '<?php echo $this->url("home")?>');" value="Lancer">
    </div>
    <div class="container_admin_game" style="display:none">
        <div class="timer">
            30
        </div>
        <div class="container_new_number">
            <span class="number">52</span>
        </div>
        <ul class="container_all_numbers">
            <?php
            for($i = 1 ; $i < 101 ; $i++){
                echo <<<HTML
                <li>
                    <div class="button">
                        {$i}
                    </div>
                </li>
HTML;

            }
            ?>
        </ul>
        <div class="container_grids">
        </div>
    </div>
    <div class="content_right">
        <div class="icone_top">
            <img src="img/connexion_inscription/icone_inscription.png" alt="">
            <div class="player_list">
                <div class="player_item">
                    <div class="left">
                        <div class="circle" style="background-color: green;"></div>
                    </div>
                    <div class="right">
                        <div class="name">ThiboJ</div>
                        <div class="stats">
                            <img src="img/game/players/victory.png" alt="img_victory">
                            10
                            <img src="img/game/players/defeat.png" alt="img_defeat">
                            7
                        </div>
                    </div>
                </div>
                <div class="player_item">
                    <div class="left">
                        <div class="circle" style="background-color: yellow;"></div>
                    </div>
                    <div class="right">
                        <div class="name">ThiboJ</div>
                        <div class="stats">
                            <img src="img/game/players/victory.png" alt="img_victory">
                            10
                            <img src="img/game/players/defeat.png" alt="img_defeat">
                            7
                        </div>
                    </div>
                </div>
                <div class="player_item">
                    <div class="left">
                        <div class="circle" style="background-color: red;"></div>
                    </div>
                    <div class="right">
                        <div class="name">ThiboJ</div>
                        <div class="stats">
                            <img src="img/game/players/victory.png" alt="img_victory">
                            10
                            <img src="img/game/players/defeat.png" alt="img_defeat">
                            7
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>