<div class="container_connexion_inscription">
    <form class="parts connexion" action="<?php echo $this->url('game');  ?>" mathod="">
        <div class="icone"></div>
        <div class="title">Connexion</div>
        <div class="champ">
            Identifiant
        </div>
        <input type="text" class="input" name="player_name">
        <br/>
        <div class="champ">
            Mot de passe
        </div>
        <input type="text" class="input" name="player_password">
        <input type="submit" value="Connexion">
    </form>
    <form class="parts inscription">
        <div class="icone"></div>
        <div class="title">Inscription</div>
        <div class="champ">
            Identifiant
        </div>
        <input type="text" class="input" name="player_name">
        <br/>
        <div class="champ">
            Mot de passe
        </div>
        <input type="text" class="input" name="player_password">
        <br/>
        <div class="champ">
            Email
        </div>
        <input type="text" class="input" name="player_email">
        <div class="colors">
            <input type="hidden" value="null" class="color_player" name="player_color">
            <div class="color">
                <div class="color_in" style="background-color:#662d91" data-color="#662d91"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#7b2e00" data-color="#7b2e00"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#0d004c" data-color="#0d004c"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#ed1c24" data-color="#ed1c24"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#4df23c" data-color="#4df23c"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#ffff00" data-color="#ffff00"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#6dcff6" data-color="#6dcff6"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#f68e56" data-color="#f68e56"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#998675" data-color="#998675"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#ec008c" data-color="#ec008c"></div>
            </div>
        </div>
        <input type="submit" value="Inscription">
    </form>
</div>
<script type="text/javascript" src="js/connexion_inscription/script.js"></script>