<div class="container_connexion_inscription">
    <div class="parts connexion">
        <div class="icone"></div>
        <div class="title">Connexion</div>
        <div class="champ">
            Identifiant
        </div>
        <input type="text" class="input">
        <br/>
        <div class="champ">
            Mot de passe
        </div>
        <input type="text" class="input">
        <input type="submit" value="Connexion">
    </div>
    <div class="parts inscription">
        <div class="icone"></div>
        <div class="title">Inscription</div>
        <div class="champ">
            Identifiant
        </div>
        <input type="text" class="input">
        <br/>
        <div class="champ">
            Mot de passe
        </div>
        <input type="text" class="input">
        <br/>
        <div class="champ">
            Email
        </div>
        <input type="text" class="input">
        <div class="colors">
            <div class="color">
                <div class="color_in" style="background-color:#662d91" data-color="#662d91"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#7b2e00" data-color="#7b2e00"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#0d004c" data-color="#0d004c"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#ed1c24" data-color="#ed1c24"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#4df23c" data-color="#4df23c"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#ffff00" data-color="#ffff00"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#6dcff6" data-color="#6dcff6"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#f68e56" data-color="#f68e56"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#998675" data-color="#998675"></div>
            </div>
            <div class="color">
                <div class="color_in" style="background-color:#ec008c" data-color="#ec008c"></div>
            </div>
        </div>
        <input type="submit" value="Inscription">
    </div>
</div>