<div class="container_connexion_inscription">
    <div class="parts connexion">
        <div class="icone"></div>
        <div class="title">Connexion</div>
        <div class="champ">
            Identifiant
        </div>
        <input type="text" class="input">
        <br/>
        <div class="champ">
            Mot de passe
        </div>
        <input type="text" class="input">
        <input type="submit" value="Connexion">
    </div>
    <div class="parts inscription">
        <div class="icone"></div>
        <div class="title">Inscription</div>
        <div class="champ">
            Identifiant
        </div>
        <input type="text" class="input">
        <br/>
        <div class="champ">
            Mot de passe
        </div>
        <input type="text" class="input">
        <br/>
        <div class="champ">
            Email
        </div>
        <input type="text" class="input">
        <input type="submit" value="Connexion">
    </div>
</div>